#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"
REPO="Acongm/fill-work-code"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/configure-vsce-pat.sh                 # prompt for PAT
  ./scripts/configure-vsce-pat.sh --from-env    # use existing $VSCE_PAT
  ./scripts/configure-vsce-pat.sh --local-only   # write .env.local only

Actions:
  1. Save VSCE_PAT to .env.local (local dev, gitignored)
  2. Upload VSCE_PAT to GitHub Actions Secret (requires gh auth login)

PAT requirements (Azure DevOps):
  Organization: All accessible organizations
  Scope: Marketplace → Manage
EOF
}

read_pat() {
  if [[ "${1:-}" == "--from-env" ]]; then
    if [[ -z "${VSCE_PAT:-}" ]]; then
      echo "error: VSCE_PAT environment variable is empty." >&2
      exit 1
    fi
    return
  fi

  if [[ -t 0 ]]; then
    read -r -s -p "Paste VSCE_PAT (input hidden): " VSCE_PAT
    echo
  else
    read -r VSCE_PAT
  fi

  if [[ -z "${VSCE_PAT:-}" || "$VSCE_PAT" == "xx" ]]; then
    echo "error: invalid PAT. Do not use placeholder 'xx'." >&2
    exit 1
  fi

  export VSCE_PAT
}

write_local_env() {
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/configure-vsce-pat.sh — do not commit
VSCE_PAT=$VSCE_PAT
EOF
  echo "Wrote $ENV_FILE (gitignored)"
}

upload_github_secret() {
  if ! command -v gh >/dev/null 2>&1; then
    echo "gh CLI not found. Install: brew install gh && gh auth login"
    echo "Or set secret manually:"
    echo "  https://github.com/$REPO/settings/secrets/actions"
    return 1
  fi

  if ! gh auth status >/dev/null 2>&1; then
    echo "Run: gh auth login"
    return 1
  fi

  printf '%s' "$VSCE_PAT" | gh secret set VSCE_PAT --repo "$REPO"
  echo "GitHub Actions secret VSCE_PAT set for $REPO"
}

main() {
  local mode="${1:-}"

  if [[ "$mode" == "-h" || "$mode" == "--help" ]]; then
    usage
    exit 0
  fi

  read_pat "$mode"
  write_local_env

  if [[ "$mode" == "--local-only" ]]; then
    echo "Local only. To publish from CI, also upload to GitHub Secrets."
    exit 0
  fi

  upload_github_secret || true
  echo
  echo "Local usage:  source .env.local && npm run publish:marketplace"
  echo "CI usage:     push tag v* or re-run Publish VS Code Extension workflow"
}

main "$@"
